version: 2

auth:
  username: $DOCKERHUB_USER
  password: $DOCKERHUB_PASSWORD  # or project environment variable reference

jobs:
  build:
    machine: true

    working_directory: ~/go/src/github.com/lotharschulz/hellogodocker
    steps:
      - checkout

      - run:
          name: Build service
          command: make

      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run:
          name: enable experimental docker deamon functionality
          command: |
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
      - run:
          name: docker pull golang & alpine base image
          command: |
            docker pull golang:1.11
      - run:
          name: docker command build
          command: |
            TAG=docker-build-0.2.$CIRCLE_BUILD_NUM
            time docker build -t lotharschulz/hellogo:$TAG .
            docker images
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            time docker push lotharschulz/hellogo:$TAG
            docker rmi -f $(docker images -q)
            time docker pull lotharschulz/hellogo:$TAG 
            docker rmi -f $(docker images -q)

      - run:
          name: docker pull golang & alpine base image
          command: |
            docker pull golang:1.11
      - run:
          name: build.docker
          command: |
            IMG=lotharschulz/hellogo
            TAG=build.docker--0.2.$CIRCLE_BUILD_NUM
            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker \n" 
            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker
            echo "docker images \n"
            docker images
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            echo "docker push $IMG:$TAG \n"
            time docker push $IMG:$TAG
            docker rmi -f $(docker images -q)
            echo "docker pull $IMG:$TAG \n"
            time docker pull $IMG:$TAG
            docker rmi -f $(docker images -q)