version: 2

auth:
  username: $DOCKERHUB_USER
  password: $DOCKERHUB_PASSWORD  # or project environment variable reference

jobs:
  build:
    machine: true

    working_directory: ~/go/src/github.com/lotharschulz/hellogodocker
    steps:
      - checkout

      - run:
          name: Build service
          command: make

      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run:
          name: enable experimental docker deamon functionality
          command: |
            sudo sh -c 'echo '\''DOCKER_OPTS="--experimental=true"'\'' >> /etc/default/docker'
            sudo service docker restart
#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#      - run:
#          name: docker command build
#          command: |
#            TAG=docker-build-0.2.$CIRCLE_BUILD_NUM
#            time docker build -t lotharschulz/hellogo:$TAG .
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            time docker push lotharschulz/hellogo:$TAG
#            docker rmi -f $(docker images -q)
#            time docker pull lotharschulz/hellogo:$TAG 
#            docker rmi -f $(docker images -q)

#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#      - run:
#          name: build.docker
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.docker--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker \n" 
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker
#            echo "docker images \n"
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#            docker pull alpine:latest
#      - run:
#          name: build.docker-cache
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.docker-cache--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-cache \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-cache
#            echo "docker images \n"
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

# docker builder
#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#            docker pull alpine:latest
#       - run:
#          name: build.dockerbuilder
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.dockerbuilder--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#            docker pull alpine:latest
#      - run:
#          name: build.dockerbuilder-cache
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.dockerbuilder-cache--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-cache \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-cache
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: build.dockerbuilder-nocache
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.dockerbuilder-nocache--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-nocache \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-nocache
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#            docker pull alpine:latest
#      - run:
#          name: build.dockerbuilder-squash
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.dockerbuilder-squash--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-squash \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-squash
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#            docker pull alpine:latest
#      - run:
#          name: build.dockerbuilder-compress
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.dockerbuilder-compress--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-compress \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-compress
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)


# alpine
#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#            docker pull alpine:latest
       - run:
          name: build.dockeralpine
          command: |
            IMG=lotharschulz/hellogo
            TAG=build.dockeralpine--0.2.$CIRCLE_BUILD_NUM
            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockeralpine \n"
            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockeralpine
            docker images
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            echo "docker push $IMG:$TAG \n"
            time docker push $IMG:$TAG
            docker rmi -f $(docker images -q)
            echo "docker pull $IMG:$TAG \n"
            time docker pull $IMG:$TAG
            docker rmi -f $(docker images -q)

#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#            docker pull alpine:latest
#      - run:
#          name: build.dockerbuilder-cache
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.dockerbuilder-cache--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-cache \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-cache
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: build.dockerbuilder-nocache
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.dockerbuilder-nocache--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-nocache \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-nocache
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#            docker pull alpine:latest
#      - run:
#          name: build.dockerbuilder-squash
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.dockerbuilder-squash--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-squash \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-squash
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: docker pull golang & alpine base image
#          command: |
#            docker pull golang:1.11
#            docker pull alpine:latest
#      - run:
#          name: build.dockerbuilder-compress
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.dockerbuilder-compress--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-compress \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.dockerbuilder-compress
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

# min
#      - run:
#          name: build.docker-min
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.docker-min--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-min \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-min
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: build.docker-min-nocache
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.docker-min-nocache--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-min-nocache \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-min-nocache
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: build.docker-min-squash
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.docker-min-squash--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-min-squash \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-min-squash
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)

#      - run:
#          name: build.docker-min-compress
#          command: |
#            IMG=lotharschulz/hellogo
#            TAG=build.docker-min-compress--0.2.$CIRCLE_BUILD_NUM
#            echo "DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-min-compress \n"
#            DOCKER_IMAGE=$IMG VERSION=$TAG time make build.docker-min-compress
#            docker images
#            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
#            echo "docker push $IMG:$TAG \n"
#            time docker push $IMG:$TAG
#            docker rmi -f $(docker images -q)
#            echo "docker pull $IMG:$TAG \n"
#            time docker pull $IMG:$TAG
#            docker rmi -f $(docker images -q)